updated unicorn init script so it waits for the pid files to be created and removed instead of a default sleep time

diff --git a/lib/greenonline/recipes/templates/unicorn_init.erb b/lib/greenonline/recipes/templates/unicorn_init.erb
--- a/lib/greenonline/recipes/templates/unicorn_init.erb
+++ b/lib/greenonline/recipes/templates/unicorn_init.erb
@@ -20,14 +20,16 @@ CMD="<%= current_path %>/bin/unicorn -D -c <%= unicorn_config %> -E <%= stage %>
 AS_USER=<%= unicorn_user %>
 set -u
 
-OLD_PIN="$PID.oldbin"
+OLD_PID="$PID.oldbin"
+
+cd $APP_ROOT || exit 1
 
 sig () {
   test -s "$PID" && kill -$1 `cat $PID`
 }
 
 oldsig () {
-  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
+  test -s $OLD_PID && kill -$1 `cat $OLD_PID`
 }
 
 run () {
@@ -38,43 +40,88 @@ run () {
   fi
 }
 
+workersig () {
+  workerpid="<%= current_path %>/tmp/pids/unicorn.worker.$2.pid"
+  test -s "$workerpid" && kill -$1 `cat $workerpid`
+}
+
 case "$1" in
 start)
-  sig 0 && echo >&2 "Already running" && exit 0
+  sig 0 && echo >&2 "Start failed: Unicorn already running! Exiting!" && exit 0
+  echo "Starting: "
   run "$CMD"
   ;;
 stop)
   sig QUIT && exit 0
-  echo >&2 "Not running"
+  echo >&2 "Stop failed: Unicorn isn't running."
   ;;
 force-stop)
   sig TERM && exit 0
-  echo >&2 "Not running"
+  echo >&2 "Force-stop failed: Unicorn isn't running"
   ;;
 restart|reload)
   sig HUP && echo reloaded OK && exit 0
-  echo >&2 "Couldn't reload, starting '$CMD' instead"
+  echo >&2 "Reload failed: executing '$CMD' "
   run "$CMD"
   ;;
 upgrade)
-  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+  if test -s $PID; then ORIG_PID=`cat $PID`; else ORIG_PID=0; fi
+
+  echo 'Original PID: ' $ORIG_PID
+
+  if sig USR2
   then
+    echo 'USR2 sent; Waiting for .oldbin'
     n=$TIMEOUT
-    while test -s $OLD_PIN && test $n -ge 0
+
+    #wait for .oldpid to be written
+    while (!(test -s $OLD_PID) && test $n -ge 0)
     do
       printf '.' && sleep 1 && n=$(( $n - 1 ))
     done
-    echo
 
-    if test $n -lt 0 && test -s $OLD_PIN
+    echo 'Waiting for new pid file'
+    #when this loop finishes, should have new pid file
+    while (!(test -s $PID ) || test -s $OLD_PID) && test $n -ge 0
+    do
+      printf '.' && sleep 1 && n=$(( $n - 1 ))
+    done
+
+    if test -s $PID
     then
-      echo >&2 "$OLD_PIN still exists after $TIMEOUT seconds"
+      NEW_PID=`cat $PID`
+    else
+      echo 'New master failed to start; see error log'
       exit 1
     fi
+
+    #timeout has elapsed, verify new pid file exists
+    if [ $ORIG_PID -eq $NEW_PID ]
+    then
+      echo
+      echo >&2 'New master failed to start; see error log'
+      exit 1
+    fi
+
+    echo 'New PID: ' $NEW_PID
+
+    #verify old master QUIT
+    echo
+    if test -s $OLD_PID
+    then
+      echo >&2 "$OLD_PID still exists after $TIMEOUT seconds"
+      exit 1
+    fi
+
+    printf 'Unicorn successfully upgraded'
     exit 0
   fi
-  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+  echo >&2 "Upgrade failed: executing '$CMD' "
   run "$CMD"
+  ;;
+kill_worker)
+  workersig QUIT $2 && exit 0
+  echo >&2 "Kill Worker failed: worker not running"
   ;;
 reopen-logs)
   sig USR1
